### ISSUE TITLE
CSS overflow

### ISSUE THREAD

**Issue by ugur-a** [jonhoo/wewerewondering#199]
I'm not at all knowledgeable in frontend stuff, but I think that's the right name for this:
![Screenshot_20241229_100603_Firefox](https://github.com/user-attachments/assets/229ed0c7-f0a8-483c-aaf5-9b5c752d9976)

This happens on the mobile version of the site (can be fixed by switching to desktop mode).

Although now that I think of it, the other posts are all displayed fine, so... did this particular poster somehow manage to make their spaces non-breaking?

**Comment by jonhoo** [comment]
I saw that too — I suspect it's a component of the URL that does it. On my phone at the moment, but I believe there is a CSS property that lets you tell it to forcibly break even such cases 🤔
